### ISSUE TITLE
Slides - Tópicos

### ISSUE THREAD

**Issue by hgp22** [hgp22/Slides-Reuniao-Aberta#1]
Deixo aqui os tópicos que falamos em reunião:

- Apresentar a equipa
- Presença do Departamento Pedagógico n'O Curso e no CeSIUM
- Overview de futuras atividades
- Workflow no CeSIUM
- Novos Colaboradores

**Comment by Pdf0** [comment]
Fico com o Workflow no CeSIUM

**Comment by hgp22** [comment]
Eu fico com a overview de futuras atividades

**Comment by danielsp45** [comment]
Eu fico com a apresentação da equipa
